version: '3'
services:

  app:
    build: .
    env_file: .env
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    command: ["sh", "-c", "/cloud-native-go/bin/migrate up && /cloud-native-go/bin/api"]

  db:
    image: postgres:alpine
    environment:
      POSTGRES_USER: myapp_user
      POSTGRES_PASSWORD: myapp_pass
      POSTGRES_DB: myapp_db
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U myapp_user -d myapp_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: always