basePath: /api/v1
definitions:
  book.DTO:
    properties:
      author:
        type: string
      description:
        type: string
      id:
        type: string
      image_url:
        type: string
      published_date:
        type: string
      title:
        type: string
    type: object
  book.Form:
    properties:
      author:
        type: string
      description:
        type: string
      image_url:
        type: string
      published_date:
        type: string
      title:
        type: string
    type: object
  err.Error:
    properties:
      error:
        type: string
    type: object
  err.Errors:
    properties:
      errors:
        items:
          $ref: '#/definitions/err.Error'
        type: array
    type: object
host: localhost:8080
info:
  contact:
    name: Velican Ercan
    url: github/velicanercan
  description: This is a sample server for Cloud Native Go Project.
  title: Cloud Native Go API
  version: "1.0"
paths:
  /.../health:
    get:
      description: Health API
      responses:
        "200":
          description: OK
      summary: Health API
      tags:
      - health
  /api/v1/books:
    get:
      consumes:
      - application/json
      description: List books
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/book.DTO'
            type: array
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: List books
      tags:
      - books
    post:
      consumes:
      - application/json
      description: Create books
      parameters:
      - description: Book form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/book.Form'
      produces:
      - application/json
      responses:
        "201":
          description: Created
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Create book
      tags:
      - books
  /api/v1/books/{id}:
    delete:
      consumes:
      - application/json
      description: Delete book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Delete book
      tags:
      - books
    get:
      consumes:
      - application/json
      description: Read book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/book.DTO'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Read book
      tags:
      - books
    put:
      consumes:
      - application/json
      description: Update book
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: string
      - description: Book form
        in: body
        name: body
        required: true
        schema:
          $ref: '#/definitions/book.Form'
      produces:
      - application/json
      responses:
        "200":
          description: OK
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/err.Error'
        "404":
          description: Not Found
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/err.Errors'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/err.Error'
      summary: Update book
      tags:
      - books
swagger: "2.0"
